### ISSUE TITLE
OpenCV Errors: DLL load failed

### ISSUE THREAD

**Issue by ghost** [nachatz/video-game-bot-cv#1]
Hi,

I'm trying to get this to run for quite some time now. However I'm stuck at installing the opencv python package.
I installed it by running: `pip install opencv-python `. However I still get this error when ttrying to run `main.py`:
```
Traceback (most recent call last):
  File "C:\Users\user\GitHub\bot\main.py", line 2, in <module>
    import cv2 as cv
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.
```

Do you know what's wrong here?

Thanks

**Comment by nachatz** [comment]
Hi! This isn't particularly something I expected to be outsourced, but rather something for others to take interest in, otherwise I'd throw up a docker container (maybe I'll do this!). You could always try to adapt this architecture to your own!

However, have you tried this: https://stackoverflow.com/questions/43184887/dll-load-failed-error-when-importing-cv2

Seems to be a relatively common issue! Wish you the best in your endeavors.
